# Generated by Django 4.0.2 on 2022-03-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name_name',
            new_name='user_name',
        ),
    ]
